# Display , Load, Save

In [3]:
#create new environments in anaconda
pip install numpy
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread('./images/flemingo.jpg')

In [3]:
print(img)

[[[188 163 119]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 [[188 163 119]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 [[188 163 119]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 ...

 [[167 134  88]
  [167 134  88]
  [167 134  88]
  ...
  [177 144  98]
  [177 144  98]
  [177 144  98]]

 [[171 141  94]
  [171 141  94]
  [172 142  95]
  ...
  [177 144  98]
  [177 144  98]
  [177 144  98]]

 [[177 147 100]
  [177 147 100]
  [178 148 101]
  ...
  [177 144  98]
  [177 144  98]
  [177 144  98]]]


In [4]:
img.shape

(640, 640, 3)

In [5]:
cv2.imshow('example',img)
cv2.waitKey(10000) # millseconds
cv2.destroyAllWindows()

In [6]:
cv2.imshow('example',img)
cv2.waitKey(0) # millseconds
cv2.destroyAllWindows()

# save an image

In [7]:
cv2.imwrite('./images/example.png',img)

True